[package]
name = "pwrs"
version = "0.1.0"
authors = ["John Wood <j@jdtw.us>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
winapi = { version = "0.3", features = ["bcrypt", "wincred", "combaseapi", "errhandlingapi", "winerror"] } 
human-panic = "0.4"
failure = "0.1"